// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AdvancedRoulette","status":true,"description":"Advanced Roulette Minigame (Straight / Red-Black / Odd-Even)","parameters":{}}
];
